In [1]:
import LanusStats as ls
import pandas as pd

In [2]:
fotmob = ls.FotMob()

In [3]:
fotmob.get_match_shotmap(4791867)

,id,eventType,teamId,playerId,playerName,x,y,min,minAdded,isBlocked,...,isSavedOffLine,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,goalMouthY,goalMouthZ,zoomRatio
0,2818528407,Miss,10081,812450,Walter Mazzanti,96.701754,42.350625,4,None,False,...,False,True,NaN,Walter,Mazzanti,Walter Mazzanti,#F8362D,6.169691e-01,0.677249,0.393012
1,2818530333,AttemptSaved,10081,1092826,Cesar Ibanez,100.448276,45.121783,7,None,False,...,False,True,443465.0,Cesar,Ibanez,Cesar Ibanez,#F8362D,6.772487e-01,0.268393,1.000000
2,2818539657,AttemptSaved,10081,981079,Matko Miljevic,81.020874,42.813125,23,None,False,...,False,False,443465.0,Matko,Miljevic,Matko Miljevic,#F8362D,1.121032e+00,0.312559,1.000000
3,2818541639,AttemptSaved,10081,812450,Walter Mazzanti,93.100000,30.135952,26,None,False,...,False,True,443465.0,Walter,Mazzanti,Walter Mazzanti,#F8362D,1.786706e+00,0.365219,1.000000
4,2818545041,Miss,10078,1435714,Santiago Gabriel Montiel,78.543204,30.492500,32,None,False,...,False,False,NaN,Santiago Gabriel,Montiel,Santiago Gabriel Montiel,#EC1C24,5.968776e-01,0.677249,0.416340
5,2818548113,AttemptSaved,10078,1086733,Sebastian Valdez,97.184211,35.982500,36,None,False,...,False,True,146801.0,Sebastian,Valdez,Sebastian Valdez,#EC1C24,4.150132e-01,0.161376,1.000000
6,2818549423,AttemptSaved,10078,1435714,Santiago Gabriel Montiel,92.300000,20.986497,38,None,True,...,False,True,NaN,Santiago Gabriel,Montiel,Santiago Gabriel Montiel,#EC1C24,3.948413e-01,0.322751,1.000000
7,2818563777,AttemptSaved,10081,981079,Matko Miljevic,80.345146,42.639687,46,None,False,...,False,False,443465.0,Matko,Miljevic,Matko Miljevic,#F8362D,1.544643e+00,0.429769,1.000000
8,2818568051,AttemptSaved,10078,1206583,Kevin Lomonaco,96.026316,38.956667,53,None,False,...,False,True,146801.0,Kevin,Lomonaco,Kevin Lomonaco,#EC1C24,2.334656e-01,0.569062,1.000000
9,2818569755,AttemptSaved,10081,981079,Matko Miljevic,78.543204,23.368662,56,None,False,...,False,False,443465.0,Matko,Miljevic,Matko Miljevic,#F8362D,1.584987e+00,0.365219,1.000000
10,2818570275,AttemptSaved,10078,1025559,Matias Gimenez Rojas,97.280702,31.941250,57,None,False,...,False,True,146801.0,Matias Gimenez,Rojas,Matias Gimenez Rojas,#EC1C24,1.342923e+00,0.151184,1.000000
11,2818572397,Miss,10081,981079,Matko Miljevic,97.859649,17.763567,62,None,False,...,False,True,NaN,Matko,Miljevic,Matko Miljevic,#F8362D,-2.220446e-16,0.077354,0.548640
12,2818573865,AttemptSaved,10078,1343374,Felipe Loyola,86.245588,33.466250,65,None,True,...,False,False,NaN,Felipe,Loyola,Felipe Loyola,#EC1C24,6.167328e-01,0.322751,1.000000
13,2818577769,Miss,10081,981079,Matko Miljevic,86.030882,35.296250,74,None,False,...,False,False,NaN,Matko,Miljevic,Matko Miljevic,#F8362D,1.154222e+00,0.677249,0.424743
14,2818579035,AttemptSaved,10081,889736,Fabio Pereyra,98.245614,37.583750,76,None,False,...,False,True,443465.0,Fabio,Pereyra,Fabio Pereyra,#F8362D,1.443783e+00,0.280284,1.000000
15,2818580707,Miss,10078,527862,Luciano Cabral,92.400000,25.013438,79,None,False,...,False,True,NaN,Luciano,Cabral,Luciano Cabral,#EC1C24,0.000000e+00,0.038911,0.818097
16,2818581969,Miss,10078,1206583,Kevin Lomonaco,79.556796,39.124762,81,None,False,...,False,False,NaN,Kevin,Lomonaco,Kevin Lomonaco,#EC1C24,2.000000e+00,0.117646,0.452661
17,2818586757,Miss,10078,522083,Pablo Galdames,78.655825,44.140892,87,None,False,...,False,False,NaN,Pablo,Galdames,Pablo Galdames,#EC1C24,0.000000e+00,0.049944,0.426111
18,2818596237,Goal,10081,795724,Leonardo Sequeira,94.000000,34.000000,91,None,False,...,False,True,443465.0,Leonardo,Sequeira,Leonardo Sequeira,#F8362D,9.226190e-02,0.290476,1.000000
19,2818596843,Post,10078,425711,Gabriel Avalos,94.000000,34.000000,92,None,False,...,False,True,NaN,Gabriel,Avalos,Gabriel Avalos,#EC1C24,6.974206e-01,0.655026,1.000000
20,2818597547,Goal,10081,845260,Tomás Ezequiel Guidara,94.000000,34.000000,93,None,False,...,False,True,443465.0,Tomás Ezequiel,Guidara,Tomás Ezequiel Guidara,#F8362D,1.847222e+00,0.032275,1.000000
21,2818598111,Goal,10078,1435714,Santiago Gabriel Montiel,94.000000,34.000000,94,None,False,...,False,True,146801.0,Santiago Gabriel,Montiel,Santiago Gabriel Montiel,#EC1C24,1.484127e+00,0.526594,1.000000
22,2818598635,Goal,10081,1237690,Marco Pellegrino,94.000000,34.000000,95,None,False,...,False,True,443465.0,Marco,Pellegrino,Marco Pellegrino,#F8362D,1.907738e+00,0.042467,1.000000
23,2818599147,Goal,10078,522083,Pablo Galdames,94.000000,34.000000,96,None,False,...,False,True,146801.0,Pablo,Galdames,Pablo Galdames,#EC1C24,2.536376e-01,0.032275,1.000000
24,2818599607,Goal,10081,981079,Matko Miljevic,94.000000,34.000000,97,None,False,...,False,True,443465.0,Matko,Miljevic,Matko Miljevic,#F8362D,1.000000e+00,0.074742,1.000000
25,2818600103,Goal,10078,1343374,Felipe Loyola,94.000000,34.000000,98,None,False,...,False,True,146801.0,Felipe,Loyola,Felipe Loyola,#EC1C24,1.201720e+00,0.139293,1.000000
26,2818600557,AttemptSaved,10081,469590,Leonardo Gil,94.000000,34.000000,99,None,False,...,False,True,443465.0,Leonardo,Gil,Leonardo Gil,#F8362D,9.596561e-01,0.536786,1.000000
27,2818601173,Goal,10078,1206583,Kevin Lomonaco,94.000000,34.000000,99,None,False,...,False,True,146801.0,Kevin,Lomonaco,Kevin Lomonaco,#EC1C24,1.729497e-01,0.032275,1.000000
28,2818601715,Goal,10081,889736,Fabio Pereyra,94.000000,34.000000,100,None,False,...,False,True,443465.0,Fabio,Pereyra,Fabio Pereyra,#F8362D,4.150132e-01,0.558869,1.000000
29,2818602225,Goal,10078,860780,Alvaro Angulo,94.000000,34.000000,101,None,False,...,False,True,146801.0,Alvaro,Angulo,Alvaro Angulo,#EC1C24,1.806878e+00,0.042467,1.000000
30,2818603029,Goal,10081,812450,Walter Mazzanti,94.000000,34.000000,102,None,False,...,False,True,443465.0,Walter,Mazzanti,Walter Mazzanti,#F8362D,4.150132e-01,0.032275,1.000000
31,2818603799,AttemptSaved,10078,1362516,Santiago Hidalgo,94.000000,34.000000,103,None,False,...,False,True,146801.0,Santiago,Hidalgo,Santiago Hidalgo,#EC1C24,1.726190e+00,0.086633,1.000000

In [4]:
liga = fotmob.fotmob_request('/leagues?id=112&ccode3=ARG')

In [11]:
df_liga_arg = pd.DataFrame(liga.json()['matches']['allMatches'])

In [16]:
df_liga_arg[df_liga_arg['round'] == '16']

,round,roundName,pageUrl,id,home,away,status
225,16,16,/matches/argentinos-juniors-vs-estudiantes/3d8...,4698060,"{'name': 'Argentinos Juniors', 'shortName': 'A...","{'name': 'Estudiantes', 'shortName': 'Estudian...","{'utcTime': '2025-05-02T18:30:00Z', 'finished'..."
226,16,16,/matches/banfield-vs-central-cordoba-de-santia...,4698065,"{'name': 'Banfield', 'shortName': 'Banfield', ...","{'name': 'Central Cordoba de Santiago', 'short...","{'utcTime': '2025-05-02T18:30:00Z', 'finished'..."
227,16,16,/matches/independiente-rivadavia-vs-defensa-y-...,4698064,"{'name': 'Independiente Rivadavia', 'shortName...","{'name': 'Defensa y Justicia', 'shortName': 'D...","{'utcTime': '2025-05-02T18:30:00Z', 'finished'..."
228,16,16,/matches/racing-club-vs-newells-old-boys/3egfk...,4698063,"{'name': 'Racing Club', 'shortName': 'Racing C...","{'name': 'Newell's Old Boys', 'shortName': 'Ne...","{'utcTime': '2025-05-02T18:30:00Z', 'finished'..."
229,16,16,/matches/belgrano-vs-union/3dc3fq#4698061,4698061,"{'name': 'Union', 'shortName': 'Union', 'id': ...","{'name': 'Belgrano', 'shortName': 'Belgrano', ...","{'utcTime': '2025-05-02T21:00:00Z', 'finished'..."
230,16,16,/matches/godoy-cruz-vs-deportivo-riestra/lwt8t...,4698057,"{'name': 'Deportivo Riestra', 'shortName': 'De...","{'name': 'Godoy Cruz', 'shortName': 'Godoy Cru...","{'utcTime': '2025-05-03T19:00:00Z', 'finished'..."
231,16,16,/matches/san-lorenzo-vs-sarmiento/aelo0d5#4698055,4698055,"{'name': 'Sarmiento', 'shortName': 'Sarmiento'...","{'name': 'San Lorenzo', 'shortName': 'San Lore...","{'utcTime': '2025-05-03T19:00:00Z', 'finished'..."
232,16,16,/matches/instituto-vs-talleres/3dde6d#4698054,4698054,"{'name': 'Talleres', 'shortName': 'Talleres', ...","{'name': 'Instituto', 'shortName': 'Instituto'...","{'utcTime': '2025-05-03T19:00:00Z', 'finished'..."
233,16,16,/matches/independiente-vs-rosario-central/3d0u...,4698056,"{'name': 'Rosario Central', 'shortName': 'Rosa...","{'name': 'Independiente', 'shortName': 'Indepe...","{'utcTime': '2025-05-03T21:30:00Z', 'finished'..."
234,16,16,/matches/lanus-vs-atletico-tucuman/6s3dgmo#469...,4698058,"{'name': 'Atletico Tucuman', 'shortName': 'Atl...","{'name': 'Lanus', 'shortName': 'Lanus', 'id': ...","{'utcTime': '2025-05-04T00:00:00Z', 'finished'..."
235,16,16,/matches/huracan-vs-barracas-central/bhhn1pa#4...,4698050,"{'name': 'Huracan', 'shortName': 'Huracan', 'i...","{'name': 'Barracas Central', 'shortName': 'Bar...","{'utcTime': '2025-05-04T00:00:00Z', 'finished'..."
236,16,16,/matches/club-atletico-platense-vs-gimnasia-lp...,4698053,"{'name': 'Gimnasia LP', 'shortName': 'Gimnasia...","{'name': 'Club Atletico Platense', 'shortName'...","{'utcTime': '2025-05-04T18:30:00Z', 'finished'..."
237,16,16,/matches/san-martin-san-juan-vs-aldosivi/ehh3i...,4698051,"{'name': 'San Martin San Juan', 'shortName': '...","{'name': 'Aldosivi', 'shortName': 'Aldosivi', ...","{'utcTime': '2025-05-04T18:30:00Z', 'finished'..."
238,16,16,/matches/boca-juniors-vs-tigre/29tnrm5#4698059,4698059,"{'name': 'Tigre', 'shortName': 'Tigre', 'id': ...","{'name': 'Boca Juniors', 'shortName': 'Boca Ju...","{'utcTime': '2025-05-04T21:00:00Z', 'finished'..."
239,16,16,/matches/river-plate-vs-velez-sarsfield/3cxts9...,4698052,"{'name': 'River Plate', 'shortName': 'River Pl...","{'name': 'Velez Sarsfield', 'shortName': 'Vele...","{'utcTime': '2025-05-04T23:30:00Z', 'finished'..."
480,16,16,/matches/huracan-vs-barracas-central/bhhn1pa#4...,4698630,"{'name': 'Barracas Central', 'shortName': 'Bar...","{'name': 'Huracan', 'shortName': 'Huracan', 'i...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
481,16,16,/matches/belgrano-vs-union/3dc3fq#4698631,4698631,"{'name': 'Belgrano', 'shortName': 'Belgrano', ...","{'name': 'Union', 'shortName': 'Union', 'id': ...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
482,16,16,/matches/boca-juniors-vs-tigre/29tnrm5#4698633,4698633,"{'name': 'Boca Juniors', 'shortName': 'Boca Ju...","{'name': 'Tigre', 'shortName': 'Tigre', 'id': ...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
483,16,16,/matches/banfield-vs-central-cordoba-de-santia...,4698627,"{'name': 'Central Cordoba de Santiago', 'short...","{'name': 'Banfield', 'shortName': 'Banfield', ...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
484,16,16,/matches/club-atletico-platense-vs-gimnasia-lp...,4698639,"{'name': 'Club Atletico Platense', 'shortName'...","{'name': 'Gimnasia LP', 'shortName': 'Gimnasia...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
485,16,16,/matches/independiente-rivadavia-vs-defensa-y-...,4698628,"{'name': 'Defensa y Justicia', 'shortName': 'D...","{'name': 'Independiente Rivadavia', 'shortName...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
486,16,16,/matches/argentinos-juniors-vs-estudiantes/3d8...,4698632,"{'name': 'Estudiantes', 'shortName': 'Estudian...","{'name': 'Argentinos Juniors', 'shortName': 'A...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
487,16,16,/matches/godoy-cruz-vs-deportivo-riestra/lwt8t...,4698635,"{'name': 'Godoy Cruz', 'shortName': 'Godoy Cru...","{'name': 'Deportivo Riestra', 'shortName': 'De...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
488,16,16,/matches/independiente-vs-rosario-central/3d0u...,4698636,"{'name': 'Independiente', 'shortName': 'Indepe...","{'name': 'Rosario Central', 'shortName': 'Rosa...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
489,16,16,/matches/instituto-vs-talleres/3dde6d#4698638,4698638,"{'name': 'Instituto', 'shortName': 'Instituto'...","{'name': 'Talleres', 'shortName': 'Talleres', ...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
490,16,16,/matches/lanus-vs-atletico-tucuman/6s3dgmo#469...,4698634,"{'name': 'Lanus', 'shortName': 'Lanus', 'id': ...","{'name': 'Atletico Tucuman', 'shortName': 'Atl...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
491,16,16,/matches/racing-club-vs-newells-old-boys/3egfk...,4698629,"{'name': 'Newell's Old Boys', 'shortName': 'Ne...","{'name': 'Racing Club', 'shortName': 'Racing C...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
492,16,16,/matches/san-lorenzo-vs-sarmiento/aelo0d5#4698637,4698637,"{'name': 'San Lorenzo', 'shortName': 'San Lore...","{'name': 'Sarmiento', 'shortName': 'Sarmiento'...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
493,16,16,/matches/san-martin-san-juan-vs-aldosivi/ehh3i...,4698641,"{'name': 'San Martin San Juan', 'shortName': '...","{'name': 'Aldosivi', 'shortName': 'Aldosivi', ...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."
494,16,16,/matches/river-plate-vs-velez-sarsfield/3cxts9...,4698640,"{'name': 'Velez Sarsfield', 'shortName': 'Vele...","{'name': 'River Plate', 'shortName': 'River Pl...","{'utcTime': '2025-11-16T21:00:00Z', 'started':..."

In [21]:
df_apertura = df_liga_arg.iloc[:240]

In [23]:
ids_partidos = df_apertura.id.unique()

In [ ]:
from tqdm import tqdm
df_total = pd.DataFrame()
for partido in tqdm(ids_partidos):
    df = fotmob.get_match_shotmap(partido)
    df_total = pd.concat([df_total, df])

In [30]:
df_total.situation.value_counts()

situation
RegularPlay        3447
FromCorner          903
SetPiece            443
FastBreak           429
FreeKick            222
ThrowInSetPiece     147
Penalty              60
IndividualPlay       51
Name: count, dtype: int64

In [33]:
pelotas_paradas = df_total[df_total['situation'].isin(['FromCorner', 'SetPiece', 'ThrowInSetPiece'])].reset_index(drop=True)

In [ ]:
pelotas_paradas

,Unnamed: 0.1,Unnamed: 0,id,eventType,teamId,playerId,playerName,x,y,min,...,isFromInsideBox,keeperId,firstName,lastName,fullName,teamColor,goalMouthY,goalMouthZ,zoomRatio,matchId
0,0,0,2768139737,AttemptSaved,10084,787284,Enzo Copetti,95.543860,34.076250,4,...,True,NaN,Enzo,Copetti,Enzo Copetti,#173B6A,8.991402e-01,0.322751,1.000000,4697863
1,1,1,2768139741,AttemptSaved,10084,1218334,Agustin Sandez,95.833333,31.026250,4,...,True,NaN,Agustin,Sandez,Agustin Sandez,#173B6A,9.394841e-01,0.322751,1.000000,4697863
2,2,2,2768140153,Miss,10227,1681472,Juan Moran,84.174272,30.220000,6,...,False,NaN,Juan,Moran,Juan Moran,#1c4294,2.000000e+00,0.610050,0.489974,4697863
3,5,5,2768142977,Miss,10227,1230664,Gonzalo Abrego,96.219298,26.169687,33,...,True,NaN,Gonzalo,Abrego,Gonzalo Abrego,#1c4294,1.278096e+00,0.677249,0.530240,4697863
4,8,8,2768144765,Miss,10227,1211360,Matias Gonzalez,91.600000,31.407500,44,...,True,NaN,Matias,Gonzalez,Matias Gonzalez,#1c4294,2.000000e+00,0.386996,0.714170,4697863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1488,5668,13,2810650259,Miss,89395,965005,Franco Toloza,95.061404,29.883810,54,...,True,NaN,Franco,Toloza,Franco Toloza,#0A6837,0.000000e+00,0.019524,0.118491,4698051
1489,5690,11,2810710931,Miss,89396,1520633,Valentin Moreno,81.471359,26.054063,45,...,False,NaN,Valentin,Moreno,Valentin Moreno,#1E448D,0.000000e+00,0.039341,0.335645,4698059
1490,5692,13,2810711671,Goal,89396,1358378,Lorenzo Scipioni,102.250000,33.313750,45,...,True,164020.0,Lorenzo,Scipioni,Lorenzo Scipioni,#1E448D,8.386243e-01,0.290476,1.000000,4698059
1491,5695,16,2810730809,AttemptSaved,89396,490660,Nehuén Paz,96.219298,32.322500,60,...,True,NaN,Nehuén,Paz,Nehuén Paz,#1E448D,7.377646e-01,0.322751,1.000000,4698059
1492,5699,20,2810739771,Miss,89396,1358378,Lorenzo Scipioni,90.800000,30.492500,86,...,True,NaN,Lorenzo,Scipioni,Lorenzo Scipioni,#1E448D,1.110223e-16,0.070394,0.331520,4698059

In [52]:
zonaa = pd.DataFrame(liga.json()['table'][0]['data']['tables'][0]['table']['all'])
zonab = pd.DataFrame(liga.json()['table'][0]['data']['tables'][1]['table']['all'])
ids_fotmob = pd.concat([zonaa,zonab])[['name', 'id']]

In [56]:
df_pelotas_paradas = pelotas_paradas.merge(ids_fotmob, left_on='teamId', right_on='id')[['eventType', 'name', 'playerName', 'x', 'y', 'min', 'expectedGoals', 'expectedGoalsOnTarget', 'shotType','situation','period','matchId']]

In [65]:
goles_pelotas_paradas = df_pelotas_paradas[df_pelotas_paradas['eventType'] == 'Goal']
goles_pelotas_paradas = goles_pelotas_paradas.groupby('name').count()['eventType']

In [67]:
df_pelotas_paradas.groupby('name').agg({
    'expectedGoals': ['count', 'sum', 'mean']
})

                            expectedGoals
                                    count       sum      mean
name
Aldosivi                               60  3.251264  0.054188
Argentinos Juniors                     52  4.294119  0.082579
Atletico Tucuman                       52  4.452938  0.085633
Banfield                               35  2.591190  0.074034
Barracas Central                       52  4.942826  0.095054
Belgrano                               43  2.637148  0.061329
Boca Juniors                           38  3.437146  0.090451
Central Cordoba de Santiago            46  3.358229  0.073005
Club Atletico Platense                 48  2.300989  0.047937
Defensa y Justicia                     39  1.576520  0.040424
Deportivo Riestra                      46  4.465936  0.097086
Estudiantes                            37  2.195734  0.059344
Gimnasia LP                            44  2.731941  0.062090
Godoy Cruz                             46  2.487537  0.054077
Huracan                                57  4.210700  0.073872
Independiente                          43  1.943891  0.045207
Independiente Rivadavia                46  3.620756  0.078712
Instituto                              59  4.625994  0.078407
Lanus                                  69  4.310021  0.062464
Newell's Old Boys                      53  4.390228  0.082834
Racing Club                            67  4.060904  0.060611
River Plate                            52  3.432190  0.066004
Rosario Central                        37  2.855477  0.077175
San Lorenzo                            44  3.008660  0.068379
San Martin San Juan                    56  3.732043  0.066644
Sarmiento                              53  3.302023  0.062302
Talleres                               64  4.054193  0.063347
Tigre                                  55  4.818215  0.087604
Union                                  66  3.727776  0.056481
Velez Sarsfield                        25  2.200181  0.088007

In [68]:
goles_pelotas_paradas

name
Aldosivi                       4
Argentinos Juniors             3
Atletico Tucuman               4
Banfield                       3
Barracas Central               8
Belgrano                       1
Boca Juniors                   3
Central Cordoba de Santiago    5
Club Atletico Platense         1
Defensa y Justicia             2
Deportivo Riestra              5
Estudiantes                    2
Gimnasia LP                    3
Godoy Cruz                     2
Huracan                        6
Independiente                  2
Independiente Rivadavia        3
Instituto                      5
Lanus                          1
Newell's Old Boys              6
Racing Club                    4
River Plate                    3
Rosario Central                7
San Lorenzo                    4
San Martin San Juan            2
Sarmiento                      3
Talleres                       5
Tigre                          4
Union                          3
Velez Sarsfield                2
Name: eventType, dtype: int64